services:
  esbuild-ts-psql:
    image: postgres:16
    container_name: esbuild-ts-psql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - esbuild-ts-psql-data:/var/lib/postgresql/data
  esbuild-redis:
    image: redis:7
    container_name: esbuild-redis
    command: /bin/sh -c "redis-server --requirepass ${EVENT_PASSWORD}"
    ports:
      - "6379:6379"
volumes:
  esbuild-ts-psql-data: